# нужно дорабатывать потерянных клиентов

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv(r"D:\Analysis Burn\Дистрибьютеры отчетность\Source\Отчеты\Москва OSHISHA\Sell_out_Москва_OSHISHA.csv")

In [4]:
if df['Дата отгрузки'].str[:4].str.match(r"\d{4}.*",).all():
    df['Дата отгрузки'] = pd.to_datetime(df['Дата отгрузки'], yearfirst=True)

In [5]:
df['month'] = df['Дата отгрузки'].dt.month
df['year'] = df['Дата отгрузки'].dt.year

### Создание сводной таблицы продаж в кг

In [197]:
general_weight = df.pivot_table(
    values='ВЕС',
    index='Сегмент',
    columns=['year','month'],
    aggfunc = 'sum'
).reset_index()

In [198]:
general_weight.rename(columns={1:"янв"}, inplace=True)
general_weight.rename(columns={2:"фев"}, inplace=True)
general_weight.rename(columns={3:"мар"}, inplace=True)
general_weight.rename(columns={4:"апр"}, inplace=True)
general_weight.rename(columns={5:"май"}, inplace=True)
general_weight.rename(columns={6:"июн"}, inplace=True)
general_weight.rename(columns={7:"июл"}, inplace=True)
general_weight.rename(columns={8:"авг"}, inplace=True)
general_weight.rename(columns={9:"сен"}, inplace=True)
general_weight.rename(columns={10:"окт"}, inplace=True)
general_weight.rename(columns={11:"ноя"}, inplace=True)
general_weight.rename(columns={12:"дек"}, inplace=True)

In [199]:
general_weight.columns = [f'{i}{"-"}{j}' for i, j in general_weight.columns]

### Создание сводной таблицы продаж в долях каждого сегмента в %

In [200]:
general_proportion = df.pivot_table(
    values='ВЕС',
    index='Сегмент',
    columns=['year','month'],
    aggfunc= 'sum'
).reset_index()

In [201]:
general_proportion.rename(columns={1:"янв"}, inplace=True)
general_proportion.rename(columns={2:"фев"}, inplace=True)
general_proportion.rename(columns={3:"мар"}, inplace=True)
general_proportion.rename(columns={4:"апр"}, inplace=True)
general_proportion.rename(columns={5:"май"}, inplace=True)
general_proportion.rename(columns={6:"июн"}, inplace=True)
general_proportion.rename(columns={7:"июл"}, inplace=True)
general_proportion.rename(columns={8:"авг"}, inplace=True)
general_proportion.rename(columns={9:"сен"}, inplace=True)
general_proportion.rename(columns={10:"окт"}, inplace=True)
general_proportion.rename(columns={11:"ноя"}, inplace=True)
general_proportion.rename(columns={12:"дек"}, inplace=True)

In [202]:
general_proportion.columns = [f'{i}{"-"}{j}' for i, j in general_proportion.columns]

In [203]:
for a in general_proportion.iloc[:,1:].columns:
    general_proportion[a] = general_proportion[a] / general_proportion[a].sum()

### Создание сводной таблицы акб

In [204]:
df.head(2)

,Торговый представитель,Код клиента,Сегмент,Клиент,Адрес доставки,Дата отгрузки,Бренд,Группа,Вкус,Граммовка,Количество шт,ВЕС,Цена,стоимость,Дистрибьютор,month,year
0,не указан,00-00008600,не указан,Фаткин Ким Родиевич,Москва г,2023-01-02,BlackBurn,BlackBurn 200 гр,Strawberry Coconut (Клубника с кокосом и эвкал...,200.0,1,0.2,1050.0,1050.0,66,1,2023
1,PRE МОПТ MSK,00-00009007,мопт,Али Севастопольская 1006 Б,"Россия, 117303, Москва г, ул Большая Юшуньская...",2023-01-04,BlackBurn,BlackBurn 200 гр,SouSep (Зелёный лимонад),200.0,10,2.0,1120.0,11200.0,66,1,2023

In [205]:
akb = df.pivot_table(
    values='Код клиента',
    index='Сегмент',
    columns=['year','month'],
    aggfunc=  'nunique'
).reset_index()

In [206]:
akb.rename(columns={1:"янв"}, inplace=True)
akb.rename(columns={2:"фев"}, inplace=True)
akb.rename(columns={3:"мар"}, inplace=True)
akb.rename(columns={4:"апр"}, inplace=True)
akb.rename(columns={5:"май"}, inplace=True)
akb.rename(columns={6:"июн"}, inplace=True)
akb.rename(columns={7:"июл"}, inplace=True)
akb.rename(columns={8:"авг"}, inplace=True)
akb.rename(columns={9:"сен"}, inplace=True)
akb.rename(columns={10:"окт"}, inplace=True)
akb.rename(columns={11:"ноя"}, inplace=True)
akb.rename(columns={12:"дек"}, inplace=True)

In [207]:
akb.columns = [f'{i}{"-"}{j}' for i, j in akb.columns]

### Создание сводной таблицы Средний чек

In [208]:
df.head(2)

,Торговый представитель,Код клиента,Сегмент,Клиент,Адрес доставки,Дата отгрузки,Бренд,Группа,Вкус,Граммовка,Количество шт,ВЕС,Цена,стоимость,Дистрибьютор,month,year
0,не указан,00-00008600,не указан,Фаткин Ким Родиевич,Москва г,2023-01-02,BlackBurn,BlackBurn 200 гр,Strawberry Coconut (Клубника с кокосом и эвкал...,200.0,1,0.2,1050.0,1050.0,66,1,2023
1,PRE МОПТ MSK,00-00009007,мопт,Али Севастопольская 1006 Б,"Россия, 117303, Москва г, ул Большая Юшуньская...",2023-01-04,BlackBurn,BlackBurn 200 гр,SouSep (Зелёный лимонад),200.0,10,2.0,1120.0,11200.0,66,1,2023

In [209]:
sr_check_temp = df.groupby(by=['Сегмент','year', 'month']).agg({'ВЕС': 'sum', 'Код клиента':'nunique'}).reset_index()

In [210]:
sr_check_temp['Средний чек'] = sr_check_temp['ВЕС'] / sr_check_temp['Код клиента']
sr_check_temp['Средний чек'] = sr_check_temp['Средний чек'].round(2)

In [228]:
sr_check_temp.head(1)

     Сегмент  year  month     ВЕС  Код клиента  Средний чек
0  vape shop  2022      1  16.575            2         8.29

In [212]:
sr_check = sr_check_temp.pivot_table(
    values='Средний чек',
    index='Сегмент',
    columns=['year','month'],
    aggfunc='sum'
).reset_index()

In [213]:
sr_check.rename(columns={1:"янв"}, inplace=True)
sr_check.rename(columns={2:"фев"}, inplace=True)
sr_check.rename(columns={3:"мар"}, inplace=True)
sr_check.rename(columns={4:"апр"}, inplace=True)
sr_check.rename(columns={5:"май"}, inplace=True)
sr_check.rename(columns={6:"июн"}, inplace=True)
sr_check.rename(columns={7:"июл"}, inplace=True)
sr_check.rename(columns={8:"авг"}, inplace=True)
sr_check.rename(columns={9:"сен"}, inplace=True)
sr_check.rename(columns={10:"окт"}, inplace=True)
sr_check.rename(columns={11:"ноя"}, inplace=True)
sr_check.rename(columns={12:"дек"}, inplace=True)

In [214]:
sr_check.columns = [f'{i}{"-"}{j}' for i, j in sr_check.columns]

In [226]:
sr_check.head(1)

,Сегмент-,2022-янв,2022-фев,2022-мар,2022-апр,2022-май,2022-июн,2022-июл,2022-авг,2022-сен,2022-окт,2022-ноя,2022-дек,2023-янв,2023-фев,2023-мар,2023-апр,2023-май,2023-июн
0,vape shop,8.29,1.46,1.27,1.12,1.64,2.07,7.18,1.21,1.74,2.3,0.9,1.03,1.2,2.5,3.89,2.88,2.73,2.02

### Потерянные клиенты

In [211]:
df.head(1)

,Торговый представитель,Код клиента,Сегмент,Клиент,Адрес доставки,Дата отгрузки,Бренд,Группа,Вкус,Граммовка,Количество шт,ВЕС,Цена,стоимость,Дистрибьютор,month,year
0,не указан,00-00008600,не указан,Фаткин Ким Родиевич,Москва г,2023-01-02,BlackBurn,BlackBurn 200 гр,Strawberry Coconut (Клубника с кокосом и эвкал...,200.0,1,0.2,1050.0,1050.0,66,1,2023

In [212]:
lost_clients = df.pivot_table(
    values='ВЕС',
    columns = ['year', 'month'],
    index = ['Сегмент','Код клиента'],
    aggfunc=lambda x: 1 if sum(x) > 0 else 0,
    fill_value=0
).reset_index()

In [213]:
lost_clients.rename(columns={1:"янв"}, inplace=True)
lost_clients.rename(columns={2:"фев"}, inplace=True)
lost_clients.rename(columns={3:"мар"}, inplace=True)
lost_clients.rename(columns={4:"апр"}, inplace=True)
lost_clients.rename(columns={5:"май"}, inplace=True)
lost_clients.rename(columns={6:"июн"}, inplace=True)
lost_clients.rename(columns={7:"июл"}, inplace=True)
lost_clients.rename(columns={8:"авг"}, inplace=True)
lost_clients.rename(columns={9:"сен"}, inplace=True)
lost_clients.rename(columns={10:"окт"}, inplace=True)
lost_clients.rename(columns={11:"ноя"}, inplace=True)
lost_clients.rename(columns={12:"дек"}, inplace=True)

In [214]:
lost_clients.columns = [f'{i}{"-"}{j}' for i, j in lost_clients.columns]

In [215]:
b = [i for i in range(lost_clients.shape[1],0,-2)]

In [216]:
b

[20, 18, 16, 14, 12, 10, 8, 6, 4, 2]

In [217]:
for i in b:
    if i == 1 or i == 2 or i == 3: 
        lost_clients[lost_clients.columns[i]] = 0
        continue

    if i != lost_clients.shape[1]:
        if i-4 != 0:
            lost_clients[lost_clients.columns[i-1]] = lost_clients.iloc[:,i-4:i].sum(axis=1)
            lost_clients[lost_clients.columns[i-1]] = np.where(lost_clients[lost_clients.columns[i-1]] > 0, 1, 0)
        if i == lost_clients.shape[1]-1:
            lost_clients[lost_clients.columns[i]] = lost_clients.iloc[:,i-4:].sum(axis=1)
            lost_clients[lost_clients.columns[i]] = np.where(lost_clients[lost_clients.columns[i]] > 0, 1, 0)

In [218]:
lost_clients

,Сегмент-,Код клиента-,2022-янв,2022-фев,2022-мар,2022-апр,2022-май,2022-июн,2022-июл,2022-авг,2022-сен,2022-окт,2022-ноя,2022-дек,2023-янв,2023-фев,2023-мар,2023-апр,2023-май,2023-июн
0,vape shop,00-00000784,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0
1,vape shop,00-00008581,0,0,0,0,0,0,1,1,0,1,1,1,0,1,1,1,0,1
2,vape shop,УТ-00011272,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0
3,vape shop,УТ-00011327,0,0,0,0,0,0,1,1,0,1,0,1,0,1,0,1,1,0
4,vape shop,УТ-00011684,0,0,0,0,0,0,1,1,0,1,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5562,табаконист,УТ-УТ000614,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
5563,табаконист,УТ-УТ000615,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
5564,табаконист,УТ-УТ000619,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
5565,табаконист,УТ-УТ000623,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
5566,табаконист,УТ-УТ000649,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1

In [223]:
lost_clients.iloc[:,2:].columns.values

array(['2022-янв', '2022-фев', '2022-мар', '2022-апр', '2022-май',
       '2022-июн', '2022-июл', '2022-авг', '2022-сен', '2022-окт',
       '2022-ноя', '2022-дек', '2023-янв', '2023-фев', '2023-мар',
       '2023-апр', '2023-май', '2023-июн'], dtype=object)

In [233]:
lost_clients

,Сегмент-,Код клиента-,2022-янв,2022-фев,2022-мар,2022-апр,2022-май,2022-июн,2022-июл,2022-авг,2022-сен,2022-окт,2022-ноя,2022-дек,2023-янв,2023-фев,2023-мар,2023-апр,2023-май,2023-июн
0,vape shop,00-00000784,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0
1,vape shop,00-00008581,0,0,0,0,0,0,1,1,0,1,1,1,0,1,1,1,0,1
2,vape shop,УТ-00011272,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0
3,vape shop,УТ-00011327,0,0,0,0,0,0,1,1,0,1,0,1,0,1,0,1,1,0
4,vape shop,УТ-00011684,0,0,0,0,0,0,1,1,0,1,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5562,табаконист,УТ-УТ000614,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
5563,табаконист,УТ-УТ000615,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
5564,табаконист,УТ-УТ000619,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
5565,табаконист,УТ-УТ000623,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
5566,табаконист,УТ-УТ000649,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1

In [235]:

lost_clients_temp = pd.melt(
    lost_clients,
    id_vars=['Сегмент-', 'Код клиента-'],
    value_vars=lost_clients.iloc[:,2:].columns.values
)

In [234]:
pd.melt(
    lost_clients,
    id_vars=['Сегмент-', 'Код клиента-'],
    value_vars=lost_clients.iloc[:,2:].columns.values
)

          Сегмент- Код клиента-  variable  value
0        vape shop  00-00000784  2022-янв      0
1        vape shop  00-00008581  2022-янв      0
2        vape shop  УТ-00011272  2022-янв      0
3        vape shop  УТ-00011327  2022-янв      0
4        vape shop  УТ-00011684  2022-янв      0
...            ...          ...       ...    ...
100201  табаконист  УТ-УТ000614  2023-июн      1
100202  табаконист  УТ-УТ000615  2023-июн      1
100203  табаконист  УТ-УТ000619  2023-июн      1
100204  табаконист  УТ-УТ000623  2023-июн      1
100205  табаконист  УТ-УТ000649  2023-июн      1

[100206 rows x 4 columns]

In [244]:
lost_clients_temp = lost_clients_temp.groupby(by=['Сегмент-', 'variable'])['value'].sum().reset_index()

In [246]:
lost_clients_temp.pivot_table(
    values = 'value',
    index = 'Сегмент-',
    columns = 'variable'
).reset_index()

variable,Сегмент-,2022-авг,2022-апр,2022-дек,2022-июл,2022-июн,2022-май,2022-мар,2022-ноя,2022-окт,2022-сен,2022-фев,2022-янв,2023-апр,2023-июн,2023-май,2023-мар,2023-фев,2023-янв
0,vape shop,27,15,22,12,20,7,9,14,23,14,3,0,27,26,21,15,23,12
1,бар/ночной клуб,0,0,14,0,0,0,0,8,0,0,0,0,23,25,17,13,17,14
2,дистрибутор,0,2,0,0,2,0,2,0,0,0,0,0,0,0,0,0,0,0
3,кальянная,723,608,809,518,699,477,428,561,760,526,346,0,849,708,659,650,803,568
4,кафе/ресторан,129,61,133,91,99,53,30,87,133,81,14,0,149,124,111,106,134,89
5,личные нужды,0,0,17,0,0,0,0,10,0,0,0,0,25,14,6,9,24,11
6,мопт,50,23,54,33,37,20,17,33,57,35,14,0,57,53,46,39,55,37
7,не указан,609,415,624,220,634,189,267,254,534,169,2,0,647,396,296,242,673,183
8,опт,1,4,3,1,4,1,4,3,1,1,2,0,4,2,2,3,5,3
9,пивной магазин,12,5,14,10,8,2,3,4,14,6,1,0,20,11,14,6,20,6
10,продуктовый магазин,6,3,5,2,3,0,1,2,7,1,0,0,4,3,4,2,4,1
11,прочее,40,23,26,13,34,11,12,0,37,14,5,0,0,0,0,0,0,0
12,спец. кальянный магазин,358,276,349,246,328,188,184,227,347,226,106,0,347,295,282,242,356,231
13,табаконист,769,515,879,455,650,339,300,498,843,493,222,0,1015,851,710,611,910,493

### Сохранение в таблицу

In [216]:
with pd.ExcelWriter(r"C:\Users\User\Desktop\Business_review.xlsx") as writer: 
    general_weight.to_excel(writer, sheet_name='Общие продажи (кг)', index=False) 
    general_proportion.to_excel(writer, sheet_name='Общие продажи (%)', index=False)
    akb.to_excel(writer, sheet_name='АКБ', index=False)
    sr_check.to_excel(writer, sheet_name='Средний чек', index=False)