In [1]:
import pandas as pd

In [9]:
sells_INN = pd.read_csv(r"D:\Analysys Burn\Википедия\БЁРН исходники\Оптовые и розничные продажи по ИНН\Оптовые и розничные продажи ИНН.csv", 
                        dtype={'ИНН продавца':str, 'ИНН покупателя' : str})

In [10]:
sells_INN.head()

,Дата операции,ИНН производителя,Наименование производителя,ИНН продавца,Наименование продавца,ИНН покупателя,Наименование покупателя,GTIN,ТН ВЭД,Наименование товара,Тип операции,Объем товара (пачек),МРЦ
0,2023-03-30,5047205725,"ООО ""БЁРН""",7743931676.0,"ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ ""АЛЬФ...",NaN,NaN,4650259250143,2403110000,Табак для кальяна (M) Banger Watermelon or mel...,Продажа конечному потребителю,1804,0
1,2023-03-30,5047205725,"ООО ""БЁРН""",7743931676.0,"ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ ""АЛЬФ...",NaN,NaN,4650259250105,2403110000,Табак для кальяна (M) Banger Passion Citrus (С...,Продажа конечному потребителю,1769,0
2,2023-03-27,5047205725,"ООО ""БЁРН""",5047205725.0,"ООО ""БЁРН""",500725710690.0,ИП Межевич Мария Дмитриевна,4650190059249,2403110000,Табак для кальяна Overdose Kashmir Citrus (Каш...,Передача между УОТ,1660,0
3,2023-03-27,5047205725,"ООО ""БЁРН""",5047205725.0,"ООО ""БЁРН""",500725710690.0,ИП Межевич Мария Дмитриевна,4650259252062,2403110000,Табак для кальяна Overdose Sweet Rose (Ягоды с...,Передача между УОТ,1660,0
4,2023-03-30,5047205725,"ООО ""БЁРН""",7743931676.0,"ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ ""АЛЬФ...",NaN,NaN,4650259250181,2403110000,Табак для кальяна (M) Banger Yummy gum (Жвачка...,Продажа конечному потребителю,1621,0

In [15]:
burn = sells_INN.loc[sells_INN['ИНН продавца'] =='5047205725.0']

In [16]:
burn.head(2)

,Дата операции,ИНН производителя,Наименование производителя,ИНН продавца,Наименование продавца,ИНН покупателя,Наименование покупателя,GTIN,ТН ВЭД,Наименование товара,Тип операции,Объем товара (пачек),МРЦ
2,2023-03-27,5047205725,"ООО ""БЁРН""",5047205725.0,"ООО ""БЁРН""",500725710690.0,ИП Межевич Мария Дмитриевна,4650190059249,2403110000,Табак для кальяна Overdose Kashmir Citrus (Каш...,Передача между УОТ,1660,0
3,2023-03-27,5047205725,"ООО ""БЁРН""",5047205725.0,"ООО ""БЁРН""",500725710690.0,ИП Межевич Мария Дмитриевна,4650259252062,2403110000,Табак для кальяна Overdose Sweet Rose (Ягоды с...,Передача между УОТ,1660,0

In [25]:
burnTH = burn['ИНН покупателя'].unique()

In [26]:
burnTH = pd.DataFrame(pd.Series(burnTH))

In [27]:
burnTH

                 0
0   500725710690.0
1     7715441408.0
2   910410435493.0
3   771977475703.0
4   772585029805.0
5   481106564441.0
6   503901106403.0
7    54604646501.0
8   500724650920.0
9   165128176030.0
10  504904832684.0
11  502986284305.0
12  781427975280.0
13    5406809232.0
14  237304896570.0
15  263606528239.0
16  151301044939.0
17  615490981930.0
18  101601626870.0
19  614306474880.0
20  470313789220.0
21    7810751939.0
22  101602387208.0
23  780251976084.0
24  220809176398.0
25  381608573800.0